[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "some-project"
authors = [{name = "Snehangshu", email = "some-project@xyz.org"}]
dynamic = ["version", "description"]
